# Generated by Django 2.2.12 on 2020-04-26 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='job_url',
            field=models.URLField(default='SOME STRING'),
        ),
        migrations.AddField(
            model_name='job',
            name='title',
            field=models.CharField(default='Title', max_length=200),
        ),
        migrations.AlterField(
            model_name='job',
            name='summary',
            field=models.CharField(default='summary', max_length=200),
        ),
    ]
