# Generated by Django 2.2.12 on 2020-05-07 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_vistor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vistor',
            name='userip',
            field=models.CharField(max_length=200),
        ),
    ]
