# Generated by Django 2.2.12 on 2020-05-08 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_auto_20200508_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vistor',
            name='visit_date',
            field=models.DateTimeField(blank=True),
        ),
    ]
