# Generated by Django 2.2.12 on 2020-05-08 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_auto_20200508_1507'),
    ]

    operations = [
        migrations.AddField(
            model_name='vistor',
            name='location',
            field=models.CharField(default='None', max_length=200),
        ),
    ]
