# Generated by Django 2.2.12 on 2020-05-11 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0008_vistor_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_label', models.CharField(default='Title', max_length=200)),
                ('image', models.ImageField(upload_to='image/')),
                ('alt_description', models.CharField(default='', max_length=200)),
                ('img_description', models.CharField(default='', max_length=200)),
                ('blog_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='jobs.Job')),
            ],
        ),
    ]
