# Generated by Django 2.2.12 on 2020-05-01 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='hashtags1',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='blog',
            name='hashtags2',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='blog',
            name='hashtags3',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='blog',
            name='title',
            field=models.CharField(default='', max_length=200),
        ),
    ]
