# Generated by Django 2.2.12 on 2020-05-03 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_testtable'),
    ]

    operations = [
        migrations.DeleteModel(
            name='testTable',
        ),
    ]
