# Generated by Django 2.2.12 on 2020-05-02 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blog_author'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subject',
        ),
    ]
