# Generated by Django 2.2.12 on 2020-05-06 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_delete_testtable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='body',
        ),
        migrations.AddField(
            model_name='blog',
            name='body1',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='blog',
            name='body2',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='blog',
            name='body3',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='blog',
            name='code1',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='blog',
            name='code2',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='blog',
            name='code3',
            field=models.TextField(default=''),
        ),
    ]
