# Generated by Django 2.2.12 on 2020-05-10 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20200506_1158'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='icon1',
            field=models.ImageField(default='', upload_to='image/'),
        ),
        migrations.AddField(
            model_name='blog',
            name='icon1link',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='blog',
            name='icon2',
            field=models.ImageField(default='', upload_to='image/'),
        ),
        migrations.AddField(
            model_name='blog',
            name='icon2link',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='blog',
            name='icon3',
            field=models.ImageField(default='', upload_to='image/'),
        ),
        migrations.AddField(
            model_name='blog',
            name='icon3link',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='blog',
            name='body1',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='blog',
            name='body2',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='blog',
            name='body3',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='blog',
            name='code1',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='blog',
            name='code2',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='blog',
            name='code3',
            field=models.TextField(blank=True, default=''),
        ),
    ]
