# Generated by Django 2.2.12 on 2020-05-26 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20200510_1452'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='extr_descript1',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='blog',
            name='extr_descript2',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='blog',
            name='extr_link1',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='blog',
            name='extr_link2',
            field=models.CharField(default='', max_length=200),
        ),
    ]
