# Generated by Django 2.2.12 on 2020-05-26 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20200526_0956'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='code_type1',
            field=models.CharField(choices=[('Code', 'Code'), ('Quote', 'Quote')], default='Code', max_length=10),
        ),
        migrations.AddField(
            model_name='blog',
            name='code_type2',
            field=models.CharField(choices=[('Code', 'Code'), ('Quote', 'Quote')], default='Code', max_length=10),
        ),
        migrations.AddField(
            model_name='blog',
            name='code_type3',
            field=models.CharField(choices=[('Code', 'Code'), ('Quote', 'Quote')], default='Code', max_length=10),
        ),
    ]
